application: mplus-1133
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: latest

builtins:
- django_wsgi: on

env_variables:
    DJANGO_SETTINGS_MODULE: 'thinkster_django_angular_boilerplate.settings'